import type { NextPage } from 'next';
import Head from 'next/head';
//import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>BWPT Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          BWPT <a href="https://nextjs.org">Portal</a>!
        </h1>
        <hr />
        <div>
          <form>
            <div className={styles.card}>
              <label>
                Email or username&nbsp;
                <input width={100} name="emailOrUsername" type="text" />
              </label>
              <br />
              <label>
                Password&nbsp;
                <input width={100} name="password" type="password" />
              </label>
              &nbsp;
              <button type="submit">Log in</button>
            </div>
          </form>
          <br />
          <form>
            <button type="button">Log in with Google</button>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
